### ISSUE TITLE
Java script blocking on rooms#index

### ISSUE THREAD

**Issue by wharesync** [WhareHauora/wharehauora-server#331] opened 2017-08-25 02:40 UTC
When viewing all rooms in a whare, the java script reloads the data every 30 seconds or so. 
This same java script is blocking. If the user clicks a link to leave a page, it doesn't happen until all rooms have finished reloading. This can be several minutes later.

**Comment by d-rivera-c** [comment] 2018-02-16 17:30
Hi :)

I'd like to contribute to the project and I tried to have a look at this since it's tagged "help wanted". I see there's a [commit](https://github.com/WhareHauora/wharehauora-server/commit/f3784d1d0129bca9fbc372812cc55cc4eeec5152#diff-8a618316c9ef9fe7cfdd86fd481c94ed) made by @Br3nda for this and I can't reproduce the issue, so I'm wondering if this still needs to be fixed? I might be looking at the wrong thing since I'm just starting with the project and I'm not familiar with Ruby, that's why I want to double check with you.

**Comment by Br3nda** [comment] 2018-02-16 21:23
Thank you @d-rivera-c. It wasn't fixed.
If you have a house with 6 rooms and view them, the javascript fetches the current readings for each room every 30 seconds. If the server is running slow, and the user clicks a link on the page (ie to leave that page) Firefox will wait for all current requests to receive their http response for reading before it finally navigates to that new page. So it can take 40 seconds to leave the page

**Comment by Br3nda** [comment] 2018-02-16 21:24
I think it got better when I turned off rails turbolinks... So maybe this was fixed after all.

**Comment by d-rivera-c** [comment] 2018-02-19 17:20
Hi @Br3nda 

thanks for answering so quickly!
So I've had another look and the code for refreshing every 30 seconds was removed in [this commit](https://github.com/WhareHauora/wharehauora-server/commit/2906fc9173c13c04d92e2c7790da2d02112908db#diff-8a618316c9ef9fe7cfdd86fd481c94edL7). I read the [pull request description](https://github.com/WhareHauora/wharehauora-server/pull/303) but there's no mention of removing that refresh as a requirement, so I'm wondering if it should be put back in or leave as is and close this issue since there's no js reload blocking anymore.

**Comment by Br3nda** [comment] 2018-02-19 21:20
Thanks for working it out. ha. it was me that broke it.
I have added a link to the wiki in our README and then added the first page to our wiki which has the state of development.
https://github.com/WhareHauora/wharehauora-server/wiki

**Comment by d-rivera-c** [comment] 2018-02-19 23:52
Ah yes, I saw that update just after commenting. Since it looks like a mayor change I won't work on any frontend stuff for now. Let me know if I can help with that.

**Closed** 2018-07-22 08:59 UTC
Labels: Backlog, bug, help wanted
