### ISSUE TITLE
Implement wireframes - UX draft

### ISSUE THREAD

**Issue by wharesync** [WhareHauora/wharehauora-server#283] opened 2017-07-26 04:18 UTC
┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;download_asset?asset_id&#x3D;391077821373054">Whare_Hauora_Web.pdf</a>

**Comment by wharesync** [comment] 2017-07-26 04:18
➤ Shiny commented:

related to #113

**Comment by wharesync** [comment] 2017-07-26 04:18
➤ Shiny commented:

![image](https://user-images.githubusercontent.com/12266/28598348-0cc29814-71f7-11e7-8b30-0ec719066eff.png)

**Comment by wharesync** [comment] 2017-08-01 20:26
➤ brenda commented:

[Amber Craig](https://app.asana.com/0/386260511942709/386260511942709) with the "analyse" button gone, how do they get through to more info on the room?

**Comment by wharesync** [comment] 2017-08-01 20:26
➤ brenda commented:

second question: What are the rules around the (1) appearing? Shall i leave that un-implemented for now and do the rest of this ?

**Comment by wharesync** [comment] 2017-08-01 20:26
➤ brenda commented:

third question: what does the search box search through?

**Comment by Br3nda** [comment] 2017-08-08 01:39
Duplicate of #281

**Closed** 2018-09-19 20:47 UTC
Labels: in progress
